### PR TITLE
Upgraded to Flutter 2.0 with full sound null-safety support

### LINKED ISSUE #3: Support null safety
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:skeleton_text`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

### PR DESCRIPTION
**Pull request by StanevPrime**

### CODE REVIEW

**Review by imlegend19 — APPROVED** [review]
Approved

**Comment by IchordeDionysos** [comment]
@imlegend19 when do you plan to publish the null-safe version to pub.dev? :)

**Comment by imlegend19** [comment]
@IchordeDionysos I'll publish today.

**Comment by imlegend19** [comment]
@IchordeDionysos the null-safety version has been published ;)

**Pull request merged**
